# This configuration file defines the hooks to be executed at each commit
repos:
# Pre-commit itself
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
        args:
        - --maxkb=5000
# Ruff linter and formatter
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.13.1
  hooks:
    # Run the linter.
    - id: ruff
      types_or: [ python, pyi, jupyter ]
      args: [ --fix ]
    # Run the formatter.
    - id: ruff-format
      types_or: [ python, pyi, jupyter ]
